// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Programsko.Models;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Automobili> Automobili { get; set; }

    public virtual DbSet<Cvjecara> Cvjecara { get; set; }

    public virtual DbSet<Dogadjaj> Dogadjaj { get; set; }

    public virtual DbSet<DogadjajCvjecara> DogadjajCvjecara { get; set; }

    public virtual DbSet<DogadjajGlazba> DogadjajGlazba { get; set; }

    public virtual DbSet<DogadjajRestoran> DogadjajRestoran { get; set; }

    public virtual DbSet<DogadjajSlasticarna> DogadjajSlasticarna { get; set; }

    public virtual DbSet<Glazba> Glazba { get; set; }

    public virtual DbSet<GlazbaPlaylist> GlazbaPlaylist { get; set; }

    public virtual DbSet<Izvjestaj> Izvjestaj { get; set; }

    public virtual DbSet<Jelo> Jelo { get; set; }

    public virtual DbSet<Ostalo> Ostalo { get; set; }

    public virtual DbSet<Playlista> Playlista { get; set; }

    public virtual DbSet<Restoran> Restoran { get; set; }

    public virtual DbSet<RestoranJelo> RestoranJelo { get; set; }

    public virtual DbSet<Salon> Salon { get; set; }

    public virtual DbSet<Slasticarna> Slasticarna { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Automobili>(entity =>
        {
            entity.HasKey(e => e.IdAutomobili).HasName("PK__AUTOMOBI__7F9AEB01E36F967F");

            entity.ToTable("AUTOMOBILI");

            entity.Property(e => e.IdAutomobili)
                .ValueGeneratedNever()
                .HasColumnName("ID_AUTOMOBILI");
            entity.Property(e => e.Cijena)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CIJENA");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.KrajAngazmana).HasColumnName("KRAJ_ANGAZMANA");
            entity.Property(e => e.Marka)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MARKA");
            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MODEL");
            entity.Property(e => e.PocAngazmana).HasColumnName("POC_ANGAZMANA");
            entity.Property(e => e.Provizija)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("PROVIZIJA");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.Automobili)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__AUTOMOBIL__ID_DO__412EB0B6");
        });

        modelBuilder.Entity<Cvjecara>(entity =>
        {
            entity.HasKey(e => e.IdCvjecara).HasName("PK__CVJECARA__6D29853895BB2EF1");

            entity.ToTable("CVJECARA");

            entity.Property(e => e.IdCvjecara)
                .ValueGeneratedNever()
                .HasColumnName("ID_CVJECARA");
            entity.Property(e => e.Adresa)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("ADRESA");
            entity.Property(e => e.Cijena)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CIJENA");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.Ime)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("IME");
            entity.Property(e => e.Provizija)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("PROVIZIJA");
            entity.Property(e => e.Telefon)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFON");
        });

        modelBuilder.Entity<Dogadjaj>(entity =>
        {
            entity.HasKey(e => e.IdDogadjaj).HasName("PK__DOGADJAJ__04A11DBA6C7CD527");

            entity.ToTable("DOGADJAJ");

            entity.Property(e => e.IdDogadjaj)
                .ValueGeneratedNever()
                .HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.Datum).HasColumnName("DATUM");
            entity.Property(e => e.IdAutomobili).HasColumnName("ID_AUTOMOBILI");
            entity.Property(e => e.IdCatering).HasColumnName("ID_CATERING");
            entity.Property(e => e.IdDc).HasColumnName("ID_DC");
            entity.Property(e => e.IdDg).HasColumnName("ID_DG");
            entity.Property(e => e.IdDs).HasColumnName("ID_DS");
            entity.Property(e => e.IdIzvjestaj).HasColumnName("ID_IZVJESTAJ");
            entity.Property(e => e.IdOstalo).HasColumnName("ID_OSTALO");
            entity.Property(e => e.IdSalon).HasColumnName("ID_SALON");
            entity.Property(e => e.Kontakt)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("KONTAKT");
            entity.Property(e => e.TipDogadjaja)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("TIP_DOGADJAJA");
        });

        modelBuilder.Entity<DogadjajCvjecara>(entity =>
        {
            entity.HasKey(e => e.IdDc).HasName("PK__DOGADJAJ__8B6237AD78AAE9F5");

            entity.ToTable("DOGADJAJ_CVJECARA");

            entity.Property(e => e.IdDc)
                .ValueGeneratedNever()
                .HasColumnName("ID_DC");
            entity.Property(e => e.IdCvjecara).HasColumnName("ID_CVJECARA");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");

            entity.HasOne(d => d.IdCvjecaraNavigation).WithMany(p => p.DogadjajCvjecara)
                .HasForeignKey(d => d.IdCvjecara)
                .HasConstraintName("FK__DOGADJAJ___ID_CV__5535A963");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.DogadjajCvjecara)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__DOGADJAJ___ID_DO__5441852A");
        });

        modelBuilder.Entity<DogadjajGlazba>(entity =>
        {
            entity.HasKey(e => e.IdDg).HasName("PK__DOGADJAJ__A1CC9CD22DF526F3");

            entity.ToTable("DOGADJAJ_GLAZBA");

            entity.Property(e => e.IdDg)
                .ValueGeneratedNever()
                .HasColumnName("ID_IZVJESTAJ");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.IdGlazba).HasColumnName("ID_GLAZBA");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.DogadjajGlazba)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__DOGADJAJ___ID_DO__48CFD27E");

            entity.HasOne(d => d.IdGlazbaNavigation).WithMany(p => p.DogadjajGlazba)
                .HasForeignKey(d => d.IdGlazba)
                .HasConstraintName("FK__DOGADJAJ___ID_GL__49C3F6B7");
        });

        modelBuilder.Entity<DogadjajRestoran>(entity =>
        {
            entity.HasKey(e => e.IdDr).HasName("PK__DOGADJAJ__8B6237BC3BDA2656");

            entity.ToTable("DOGADJAJ_RESTORAN");

            entity.Property(e => e.IdDr)
                .ValueGeneratedNever()
                .HasColumnName("ID_DR");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.IdRestoran).HasColumnName("ID_RESTORAN");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.DogadjajRestoran)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__DOGADJAJ___ID_DO__5FB337D6");

            entity.HasOne(d => d.IdRestoranNavigation).WithMany(p => p.DogadjajRestoran)
                .HasForeignKey(d => d.IdRestoran)
                .HasConstraintName("FK__DOGADJAJ___ID_RE__60A75C0F");
        });

        modelBuilder.Entity<DogadjajSlasticarna>(entity =>
        {
            entity.HasKey(e => e.IdDs).HasName("PK__DOGADJAJ__8B6237BDE1E82B2C");

            entity.ToTable("DOGADJAJ_SLASTICARNA");

            entity.Property(e => e.IdDs)
                .ValueGeneratedNever()
                .HasColumnName("ID_DS");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.IdSlasticarna).HasColumnName("ID_SLASTICARNA");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.DogadjajSlasticarna)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__DOGADJAJ___ID_DO__59FA5E80");

            entity.HasOne(d => d.IdSlasticarnaNavigation).WithMany(p => p.DogadjajSlasticarna)
                .HasForeignKey(d => d.IdSlasticarna)
                .HasConstraintName("FK__DOGADJAJ___ID_SL__5AEE82B9");
        });

        modelBuilder.Entity<Glazba>(entity =>
        {
            entity.HasKey(e => e.IdGlazba).HasName("PK__GLAZBA__9BBB6CA92215D1F3");

            entity.ToTable("GLAZBA");

            entity.Property(e => e.IdGlazba)
                .ValueGeneratedNever()
                .HasColumnName("ID_GLAZBA");
            entity.Property(e => e.Cijena)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CIJENA");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.IdDogadjajGlazba).HasColumnName("ID_DOGADJAJ_GLAZBA");
            entity.Property(e => e.Ime)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("IME");
            entity.Property(e => e.KrajAngazmana).HasColumnName("KRAJ_ANGAZMANA");
            entity.Property(e => e.PocAngazmana).HasColumnName("POC_ANGAZMANA");
            entity.Property(e => e.Provizija)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("PROVIZIJA");
            entity.Property(e => e.Telefon)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFON");
        });

        modelBuilder.Entity<GlazbaPlaylist>(entity =>
        {
            entity.HasKey(e => e.IdGp).HasName("PK__GLAZBA_P__8B62CF149E6780EC");

            entity.ToTable("GLAZBA_PLAYLIST");

            entity.Property(e => e.IdGp)
                .ValueGeneratedNever()
                .HasColumnName("ID_GP");
            entity.Property(e => e.IdGlazba).HasColumnName("ID_GLAZBA");
            entity.Property(e => e.IdPlaylista).HasColumnName("ID_PLAYLISTA");

            entity.HasOne(d => d.IdGlazbaNavigation).WithMany(p => p.GlazbaPlaylist)
                .HasForeignKey(d => d.IdGlazba)
                .HasConstraintName("FK__GLAZBA_PL__ID_GL__4E88ABD4");

            entity.HasOne(d => d.IdPlaylistaNavigation).WithMany(p => p.GlazbaPlaylist)
                .HasForeignKey(d => d.IdPlaylista)
                .HasConstraintName("FK__GLAZBA_PL__ID_PL__4F7CD00D");
        });

        modelBuilder.Entity<Izvjestaj>(entity =>
        {
            entity.HasKey(e => e.IdIzvjestaj).HasName("PK__IZVJESTA__A1CC9CD22E4818CB");

            entity.ToTable("IZVJESTAJ");

            entity.Property(e => e.IdIzvjestaj)
                .ValueGeneratedNever()
                .HasColumnName("ID_IZVJESTAJ");
            entity.Property(e => e.DatumKreiranja).HasColumnName("DATUM_KREIRANJA");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.Podatci)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("PODATCI");
            entity.Property(e => e.TipIzvjestaja)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("TIP_IZVJESTAJA");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.Izvjestaj)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__IZVJESTAJ__ID_DO__3B75D760");
        });

        modelBuilder.Entity<Jelo>(entity =>
        {
            entity.HasKey(e => e.IdJelo).HasName("PK__JELO__8681A1F58002180C");

            entity.ToTable("JELO");

            entity.Property(e => e.IdJelo)
                .ValueGeneratedNever()
                .HasColumnName("ID_JELO");
            entity.Property(e => e.Cijena)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CIJENA");
            entity.Property(e => e.Naziv)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NAZIV");
            entity.Property(e => e.Opis)
                .HasColumnType("text")
                .HasColumnName("OPIS");
            entity.Property(e => e.Sastojci)
                .HasColumnType("text")
                .HasColumnName("SASTOJCI");
            entity.Property(e => e.VrstaJela)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("VRSTA_JELA");
        });

        modelBuilder.Entity<Ostalo>(entity =>
        {
            entity.HasKey(e => e.IdOstalo).HasName("PK__OSTALO__684531F8EB7D4843");

            entity.ToTable("OSTALO");

            entity.Property(e => e.IdOstalo)
                .ValueGeneratedNever()
                .HasColumnName("ID_OSTALO");
            entity.Property(e => e.Adresa)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("ADRESA");
            entity.Property(e => e.Cijena)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CIJENA");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.Ime)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("IME");
            entity.Property(e => e.KrajAngazmana).HasColumnName("KRAJ_ANGAZMANA");
            entity.Property(e => e.NazivUsuge)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NAZIV_USUGE");
            entity.Property(e => e.PocAngazmana).HasColumnName("POC_ANGAZMANA");
            entity.Property(e => e.Provizija)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("PROVIZIJA");
            entity.Property(e => e.Telefon)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFON");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.Ostalo)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__OSTALO__ID_DOGAD__440B1D61");
        });

        modelBuilder.Entity<Playlista>(entity =>
        {
            entity.HasKey(e => e.IdPlaylista).HasName("PK__PLAYLIST__51DC1DD0335F7DAA");

            entity.ToTable("PLAYLISTA");

            entity.Property(e => e.IdPlaylista)
                .ValueGeneratedNever()
                .HasColumnName("ID_PLAYLISTA");
            entity.Property(e => e.Naziv)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NAZIV");
            entity.Property(e => e.Opis)
                .HasColumnType("text")
                .HasColumnName("OPIS");
            entity.Property(e => e.Trajanje).HasColumnName("TRAJANJE");
            entity.Property(e => e.Url)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("URL");
        });

        modelBuilder.Entity<Restoran>(entity =>
        {
            entity.HasKey(e => e.IdRestoran).HasName("PK__RESTORAN__A03B54630FD6481E");

            entity.ToTable("RESTORAN");

            entity.Property(e => e.IdRestoran)
                .ValueGeneratedNever()
                .HasColumnName("ID_RESTORAN");
            entity.Property(e => e.Kontakt)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("KONTAKT");
            entity.Property(e => e.Lokacija)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("LOKACIJA");
            entity.Property(e => e.Mail)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("MAIL");
            entity.Property(e => e.Mjesto)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("MJESTO");
            entity.Property(e => e.Naziv)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NAZIV");
        });

        modelBuilder.Entity<RestoranJelo>(entity =>
        {
            entity.HasKey(e => e.IdRj).HasName("PK__RESTORAN__8B6381EA11130C3C");

            entity.ToTable("RESTORAN_JELO");

            entity.Property(e => e.IdRj)
                .ValueGeneratedNever()
                .HasColumnName("ID_RJ");
            entity.Property(e => e.IdJelo).HasColumnName("ID_JELO");
            entity.Property(e => e.IdRestoran).HasColumnName("ID_RESTORAN");

            entity.HasOne(d => d.IdJeloNavigation).WithMany(p => p.RestoranJelo)
                .HasForeignKey(d => d.IdJelo)
                .HasConstraintName("FK__RESTORAN___ID_JE__66603565");

            entity.HasOne(d => d.IdRestoranNavigation).WithMany(p => p.RestoranJelo)
                .HasForeignKey(d => d.IdRestoran)
                .HasConstraintName("FK__RESTORAN___ID_RE__656C112C");
        });

        modelBuilder.Entity<Salon>(entity =>
        {
            entity.HasKey(e => e.IdSalon).HasName("PK__SALON__E77AB92A33B633D4");

            entity.ToTable("SALON");

            entity.Property(e => e.IdSalon)
                .ValueGeneratedNever()
                .HasColumnName("ID_SALON");
            entity.Property(e => e.Adresa)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("ADRESA");
            entity.Property(e => e.BrojMjesta).HasColumnName("BROJ_MJESTA");
            entity.Property(e => e.Cijena)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CIJENA");
            entity.Property(e => e.IdDogadjaj).HasColumnName("ID_DOGADJAJ");
            entity.Property(e => e.Ime)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("IME");
            entity.Property(e => e.KrajAngazmana).HasColumnName("KRAJ_ANGAZMANA");
            entity.Property(e => e.PocAngazmana).HasColumnName("POC_ANGAZMANA");
            entity.Property(e => e.Provizija)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("PROVIZIJA");
            entity.Property(e => e.Telefon)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFON");
            entity.Property(e => e.Velicina)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("VELICINA");

            entity.HasOne(d => d.IdDogadjajNavigation).WithMany(p => p.Salon)
                .HasForeignKey(d => d.IdDogadjaj)
                .HasConstraintName("FK__SALON__ID_DOGADJ__3E52440B");
        });

        modelBuilder.Entity<Slasticarna>(entity =>
        {
            entity.HasKey(e => e.IdSlasticarna).HasName("PK__SLASTICA__942C50266FB27336");

            entity.ToTable("SLASTICARNA");

            entity.Property(e => e.IdSlasticarna)
                .ValueGeneratedNever()
                .HasColumnName("ID_SLASTICARNA");
            entity.Property(e => e.Adresa)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("ADRESA");
            entity.Property(e => e.Cijena)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("CIJENA");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.Ime)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("IME");
            entity.Property(e => e.Provizija)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("PROVIZIJA");
            entity.Property(e => e.Telefon)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("TELEFON");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}