// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;
    
public partial class Automobili
{
    public int IdAutomobili { get; set; }

    public string Marka { get; set; }

    public string Model { get; set; }

    public decimal Cijena { get; set; }

    public decimal? Provizija { get; set; }

    public DateOnly? PocAngazmana { get; set; }

    public DateOnly? KrajAngazmana { get; set; }

    public int? IdDogadjaj { get; set; }

    public virtual Dogadjaj IdDogadjajNavigation { get; set; }
}