// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models
{
    public partial class DogadjajGlazba
    {
        public int IdDg { get; set; } // Primary key

        public int? IdDogadjaj { get; set; }

        public int? IdGlazba { get; set; }

        public DateOnly? PocAngazmana { get; set; }  // Added field

        public DateOnly? KrajAngazmana { get; set; }  // Added field

        public virtual Dogadjaj IdDogadjajNavigation { get; set; }

        public virtual Glazba IdGlazbaNavigation { get; set; }
    }
}
