// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class DogadjajSlasticarna
{
    public int IdDs { get; set; }

    public int? IdDogadjaj { get; set; }

    public int? IdSlasticarna { get; set; }

    public virtual Dogadjaj IdDogadjajNavigation { get; set; }

    public virtual Slasticarna IdSlasticarnaNavigation { get; set; }
}