// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class Dogadjaj
{
    public int IdDogadjaj { get; set; }

    public DateOnly Datum { get; set; }

    public string Kontakt { get; set; }

    public string TipDogadjaja { get; set; }

    public int? IdDg { get; set; }

    public int? IdDc { get; set; }

    public int? IdDs { get; set; }

    public int? IdOstalo { get; set; }

    public int? IdIzvjestaj { get; set; }

    public int? IdAutomobili { get; set; }

    public int? IdSalon { get; set; }

    public int? IdCatering { get; set; }

    public virtual ICollection<Automobili> Automobili { get; set; } = new List<Automobili>();

    public virtual ICollection<DogadjajCvjecara> DogadjajCvjecara { get; set; } = new List<DogadjajCvjecara>();

    public virtual ICollection<DogadjajGlazba> DogadjajGlazba { get; set; } = new List<DogadjajGlazba>();

    public virtual ICollection<DogadjajRestoran> DogadjajRestoran { get; set; } = new List<DogadjajRestoran>();

    public virtual ICollection<DogadjajSlasticarna> DogadjajSlasticarna { get; set; } = new List<DogadjajSlasticarna>();

    public virtual ICollection<Izvjestaj> Izvjestaj { get; set; } = new List<Izvjestaj>();

    public virtual ICollection<Ostalo> Ostalo { get; set; } = new List<Ostalo>();

    public virtual ICollection<Salon> Salon { get; set; } = new List<Salon>();
}