// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class DogadjajRestoran
{
    public int IdDr { get; set; }

    public int? IdDogadjaj { get; set; }

    public int? IdRestoran { get; set; }

    public virtual Dogadjaj IdDogadjajNavigation { get; set; }

    public virtual Restoran IdRestoranNavigation { get; set; }
}