// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class DogadjajGlazba
{
    public int IdIzvjestaj { get; set; }

    public int? IdDogadjaj { get; set; }

    public int? IdGlazba { get; set; }

    public virtual Dogadjaj IdDogadjajNavigation { get; set; }

    public virtual Glazba IdGlazbaNavigation { get; set; }
}