// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class GlazbaPlaylist
{
    public int IdGp { get; set; }

    public int? IdGlazba { get; set; }

    public int? IdPlaylista { get; set; }

    public virtual Glazba IdGlazbaNavigation { get; set; }

    public virtual Playlista IdPlaylistaNavigation { get; set; }
}