// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class Izvjestaj
{
    public int IdIzvjestaj { get; set; }

    public string TipIzvjestaja { get; set; }

    public string Podatci { get; set; }

    public DateOnly DatumKreiranja { get; set; }

    public int? IdDogadjaj { get; set; }

    public virtual Dogadjaj IdDogadjajNavigation { get; set; }
}