// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class Ostalo
{
    public int IdOstalo { get; set; }

    public string Ime { get; set; }

    public string Adresa { get; set; }

    public string Telefon { get; set; }

    public string Email { get; set; }

    public decimal? Provizija { get; set; }

    public decimal Cijena { get; set; }

    public string NazivUsuge { get; set; }

    public DateOnly? PocAngazmana { get; set; }

    public DateOnly? KrajAngazmana { get; set; }

    public int? IdDogadjaj { get; set; }

    public virtual Dogadjaj IdDogadjajNavigation { get; set; }
}