// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class Playlista
{
    public int IdPlaylista { get; set; }

    public string Naziv { get; set; }

    public string Opis { get; set; }

    public string Url { get; set; }

    public TimeOnly? Trajanje { get; set; }

    public virtual ICollection<GlazbaPlaylist> GlazbaPlaylist { get; set; } = new List<GlazbaPlaylist>();
}