// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class Restoran
{
    public int IdRestoran { get; set; }

    public string Naziv { get; set; }

    public string Lokacija { get; set; }

    public string Kontakt { get; set; }

    public string Mail { get; set; }

    public string Mjesto { get; set; }

    public virtual ICollection<DogadjajRestoran> DogadjajRestoran { get; set; } = new List<DogadjajRestoran>();

    public virtual ICollection<RestoranJelo> RestoranJelo { get; set; } = new List<RestoranJelo>();
}