// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class RestoranJelo
{
    public int IdRj { get; set; }

    public int? IdRestoran { get; set; }

    public int? IdJelo { get; set; }

    public virtual Jelo IdJeloNavigation { get; set; }

    public virtual Restoran IdRestoranNavigation { get; set; }
}