// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Programsko.Models;

public partial class Slasticarna
{
    public int IdSlasticarna { get; set; }

    public string Ime { get; set; }

    public string Adresa { get; set; }

    public string Telefon { get; set; }

    public string Email { get; set; }

    public decimal? Provizija { get; set; }

    public decimal Cijena { get; set; }

    public virtual ICollection<DogadjajSlasticarna> DogadjajSlasticarna { get; set; } = new List<DogadjajSlasticarna>();
}