import React, { useState } from "react";
import axios from "axios";

const Jelo = () => {
  const [formData, setFormData] = useState({
    id_jelo: "",         // Optional if auto-generated by backend
    naziv: "",
    opis: "",
    cijena: "",
    vrsta_jela: "",
    sastojci: "",
  });

  const [message, setMessage] = useState("");

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post("http://localhost:5269/api/jelo", formData);
      if (response.status === 200 || response.status === 201) {
        setMessage("Podaci uspješno poslani!");
        setFormData({
          id_jelo: "",       // Reset field
          naziv: "",
          opis: "",
          cijena: "",
          vrsta_jela: "",
          sastojci: "",
        });
      }
    } catch (error) {
      setMessage("Greška prilikom slanja podataka.");
      console.error("Error:", error);
    }
  };

  return (
    <div style={{ maxWidth: "400px", margin: "auto", textAlign: "center" }}>
      <h2>Unos Jela</h2>
      <form onSubmit={handleSubmit}>
        <input type="text" name="id_jelo" placeholder="ID Jelo (optional)" value={formData.id_jelo} onChange={handleChange} />
        <input type="text" name="naziv" placeholder="Naziv Jela" value={formData.naziv} onChange={handleChange} required />
        <textarea name="opis" placeholder="Opis Jela" value={formData.opis} onChange={handleChange} required />
        <input type="number" name="cijena" placeholder="Cijena" value={formData.cijena} onChange={handleChange} required />
        <input type="text" name="vrsta_jela" placeholder="Vrsta Jela" value={formData.vrsta_jela} onChange={handleChange} required />
        <textarea name="sastojci" placeholder="Sastojci" value={formData.sastojci} onChange={handleChange} required />
        <button type="submit">Pošalji</button>
      </form>
      {message && <p>{message}</p>}
    </div>
  );
};

export default Jelo;