import React, { useState } from "react";
import axios from "axios";

const Playlista = () => {
  const [formData, setFormData] = useState({
    id_playlista: "", // Optional if auto-generated by backend
    naziv: "",
    opis: "",
    url: "",
    trajanje: "",
  });

  const [message, setMessage] = useState("");

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post(
        "http://localhost:5269/api/playlista",
        formData,
      );
      if (response.status === 200 || response.status === 201) {
        setMessage("Podatci uspješno poslani!");
        setFormData({
          id_playlista: "", // Reset field
          naziv: "",
          opis: "",
          url: "",
          trajanje: "",
        });
      }
    } catch (error) {
      setMessage("Greška prilikom slanja podataka.");
      console.error("Error:", error);
    }
  };

  return (
    <div style={{ maxWidth: "400px", margin: "auto", textAlign: "center" }}>
      <h2>Unos Podataka za Playlistu</h2>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          name="id_playlista"
          placeholder="ID Playliste (optional)"
          value={formData.id_playlista}
          onChange={handleChange}
        />
        <input
          type="text"
          name="naziv"
          placeholder="Naziv"
          value={formData.naziv}
          onChange={handleChange}
          required
        />
        <textarea
          name="opis"
          placeholder="Opis"
          value={formData.opis}
          onChange={handleChange}
          required
        />
        <input
          type="url"
          name="url"
          placeholder="URL"
          value={formData.url}
          onChange={handleChange}
          required
        />
        <input
          type="time"
          name="trajanje"
          placeholder="Trajanje"
          value={formData.trajanje}
          onChange={handleChange}
          required
        />
        <button type="submit">Pošalji</button>
      </form>
      {message && <p>{message}</p>}
    </div>
  );
};

export default Playlista;
