import React, { useState } from "react";
import axios from "axios";

const Restoran = () => {
  const [formData, setFormData] = useState({
    id_restoran: "",       // Optional if auto-generated by backend
    naziv: "",
    lokacija: "",
    kontakt: "",
    mail: "",
    mjesto: "",
  });

  const [message, setMessage] = useState("");

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post("http://localhost:5269/api/restoran", formData);
      if (response.status === 200 || response.status === 201) {
        setMessage("Podaci uspješno poslani!");
        setFormData({
          id_restoran: "",   // Reset field
          naziv: "",
          lokacija: "",
          kontakt: "",
          mail: "",
          mjesto: "",
        });
      }
    } catch (error) {
      setMessage("Greška prilikom slanja podataka.");
      console.error("Error:", error);
    }
  };

  return (
    <div style={{ maxWidth: "400px", margin: "auto", textAlign: "center" }}>
      <h2>Unos Podataka za Restoran</h2>
      <form onSubmit={handleSubmit}>
        <input type="text" name="id_restoran" placeholder="ID Restorana (optional)" value={formData.id_restoran} onChange={handleChange} />
        <input type="text" name="naziv" placeholder="Naziv" value={formData.naziv} onChange={handleChange} required />
        <input type="text" name="lokacija" placeholder="Lokacija" value={formData.lokacija} onChange={handleChange} required />
        <input type="tel" name="kontakt" placeholder="Kontakt" value={formData.kontakt} onChange={handleChange} required />
        <input type="email" name="mail" placeholder="E-mail" value={formData.mail} onChange={handleChange} required />
        <input type="text" name="mjesto" placeholder="Mjesto" value={formData.mjesto} onChange={handleChange} required />
        <button type="submit">Pošalji</button>
      </form>
      {message && <p>{message}</p>}
    </div>
  );
};

export default Restoran;