import React, { useState } from "react";
import axios from "axios";

const Salon = () => {
  const [formData, setFormData] = useState({
    id_salon: "",           // Optional if auto-generated by backend
    ime: "",
    adresa: "",
    telefon: "",
    provizija: "",
    cijena: "",
    broj_mjesta: "",
    velicina: "",
    poc_angazmana: "",
    kraj_angazmana: "",
    id_dogadjaj: "",
  });

  const [message, setMessage] = useState("");

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post("http://localhost:5269/api/salon", formData);
      if (response.status === 200 || response.status === 201) {
        setMessage("Podaci uspješno poslani!");
        setFormData({
          id_salon: "",         // Reset field
          ime: "",
          adresa: "",
          telefon: "",
          provizija: "",
          cijena: "",
          broj_mjesta: "",
          velicina: "",
          poc_angazmana: "",
          kraj_angazmana: "",
          id_dogadjaj: "",
        });
      }
    } catch (error) {
      setMessage("Greška prilikom slanja podataka.");
      console.error("Error:", error);
    }
  };

  return (
    <div style={{ maxWidth: "400px", margin: "auto", textAlign: "center" }}>
      <h2>Unos Podataka za Salon</h2>
      <form onSubmit={handleSubmit}>
        <input type="text" name="id_salon" placeholder="ID Salon (optional)" value={formData.id_salon} onChange={handleChange} />
        <input type="text" name="ime" placeholder="Ime" value={formData.ime} onChange={handleChange} required />
        <input type="text" name="adresa" placeholder="Adresa" value={formData.adresa} onChange={handleChange} required />
        <input type="text" name="telefon" placeholder="Telefon" value={formData.telefon} onChange={handleChange} required />
        <input type="number" name="provizija" placeholder="Provizija" value={formData.provizija} onChange={handleChange} required />
        <input type="number" name="cijena" placeholder="Cijena" value={formData.cijena} onChange={handleChange} required />
        <input type="number" name="broj_mjesta" placeholder="Broj Mjesta" value={formData.broj_mjesta} onChange={handleChange} required />
        <input type="number" name="velicina" placeholder="Velicina" value={formData.velicina} onChange={handleChange} required />
        <input type="date" name="poc_angazmana" placeholder="Početak Angažmana" value={formData.poc_angazmana} onChange={handleChange} required />
        <input type="date" name="kraj_angazmana" placeholder="Kraj Angažmana" value={formData.kraj_angazmana} onChange={handleChange} required />
        <input type="number" name="id_dogadjaj" placeholder="ID Dogadjaj" value={formData.id_dogadjaj} onChange={handleChange} required />
        
        <button type="submit">Pošalji</button>
      </form>
      {message && <p>{message}</p>}
    </div>
  );
};

export default Salon;