import React, { useState } from "react";
import axios from "axios";

const Slasticarna = () => {
  const [formData, setFormData] = useState({
    id_slasticarna: "",   // Optional if auto-generated by backend
    ime: "",
    adresa: "",
    telefon: "",
    email: "",
    provizija: "",
    cijena: "",
  });

  const [message, setMessage] = useState("");

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post("http://localhost:5269/api/slasticarna", formData);
      if (response.status === 200 || response.status === 201) {
        setMessage("Podaci uspješno poslani!");
        setFormData({
          id_slasticarna: "",         // Reset field
          ime: "",
          adresa: "",
          telefon: "",
          email: "",
          provizija: "",
          cijena: "",
        });
      }
    } catch (error) {
      setMessage("Greška prilikom slanja podataka.");
      console.error("Error:", error);
    }
  };

  return (
    <div style={{ maxWidth: "400px", margin: "auto", textAlign: "center" }}>
      <h2>Unos Podataka za Slastičarnu</h2>
      <form onSubmit={handleSubmit}>
        <input type="text" name="id_slasticarna" placeholder="ID Slastičarna (optional)" value={formData.id_slasticarna} onChange={handleChange} />
        <input type="text" name="ime" placeholder="Ime" value={formData.ime} onChange={handleChange} required />
        <input type="text" name="adresa" placeholder="Adresa" value={formData.adresa} onChange={handleChange} required />
        <input type="text" name="telefon" placeholder="Telefon" value={formData.telefon} onChange={handleChange} required />
        <input type="email" name="email" placeholder="Email" value={formData.email} onChange={handleChange} required />
        <input type="number" name="provizija" placeholder="Provizija" value={formData.provizija} onChange={handleChange} required />
        <input type="number" name="cijena" placeholder="Cijena" value={formData.cijena} onChange={handleChange} required />
        
        <button type="submit">Pošalji</button>
      </form>
      {message && <p>{message}</p>}
    </div>
  );
};

export default Slasticarna;